server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userform?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: wiki
    password: wiki
    driver-class-name: com.mysql.cj.jdbc.Driver
