GET http://localhost:8080/ebook/getAll
Accept: application/json

###分隔符

GET http://localhost:8080/ebook/getList?current=1&pageSize=1000
Accept: application/json

###

GET http://localhost:8080/category/getAll
Accept: application/json

###